cartesian_variable_impedance_controller:
    type: franka_human_friendly_controllers/CartesianVariableImpedanceController
    arm_id: $(arg arm_id)
    joint_names:
        - $(arg arm_id)_joint1
        - $(arg arm_id)_joint2
        - $(arg arm_id)_joint3
        - $(arg arm_id)_joint4
        - $(arg arm_id)_joint5
        - $(arg arm_id)_joint6
        - $(arg arm_id)_joint7
joint_variable_impedance_controller:
    type: franka_human_friendly_controllers/JointVariableImpedanceController
    arm_id: $(arg arm_id)
    joint_names:
        - $(arg arm_id)_joint1
        - $(arg arm_id)_joint2
        - $(arg arm_id)_joint3
        - $(arg arm_id)_joint4
        - $(arg arm_id)_joint5
        - $(arg arm_id)_joint6
        - $(arg arm_id)_joint7
cartesian_variable_impedance_external_model_controller:
    type: franka_human_friendly_controllers/CartesianVariableImpedanceExternalModelController
    arm_id: $(arg arm_id)
    joint_names:
        - $(arg arm_id)_joint1
        - $(arg arm_id)_joint2
        - $(arg arm_id)_joint3
        - $(arg arm_id)_joint4
        - $(arg arm_id)_joint5
        - $(arg arm_id)_joint6
        - $(arg arm_id)_joint7
cartesian_fixed_impedance_controller:
    type: franka_human_friendly_controllers/CartesianFixedImpedanceController
    arm_id: $(arg arm_id)
